"""Parser/loader for the GA DCH weekly "CON Tracking Report" PDF.

The report is organized by lifecycle section (Letters of Intent, New
Applications, ..., Letters of Determination); each entry carries a docket
number, applicant, project description, dates, site/county, estimated cost,
and opposition status.

ALL layout assumptions live in the module-level tables below
(ARTIFACT_PATTERNS, REPORT_DATE_PATTERNS, SECTION_PATTERNS,
ENTRY_START_PATTERNS, FIELD_PATTERNS, DATE_PATTERNS, cost regexes) so that
re-tuning against the real DCH PDF is a table edit, not a rewrite.

Built against the synthetic fixture tests/fixtures/sample_weekly_report.pdf
(generated by tests/fixtures/make_weekly_report_fixture.py); re-tune the
tables when a real DCH sample is available.

CLI:
    python -m ingest.weekly_report_parser report.pdf [--apply] [--out events.json]
"""

import argparse
import hashlib
import json
import os
import re
import sys
from dataclasses import asdict, dataclass
from datetime import date, datetime
from decimal import Decimal, InvalidOperation

from common.docket import extract_dockets, normalize_docket
from common.vocab import REPORT_SECTIONS, match_county

# ---------------------------------------------------------------------------
# Layout assumption tables — edit these to re-tune against the real DCH PDF.
# ---------------------------------------------------------------------------

# Lines that are page furniture, not content: page footers, "(continued)"
# running headers, and decoration/underline rows. Stripped before any parsing
# so entries that span page breaks re-join cleanly.
ARTIFACT_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^\s*Page\s+\d+(?:\s+of\s+\d+)?\s*$", re.IGNORECASE),
    re.compile(r".*\(continued\)\s*$", re.IGNORECASE),
    re.compile(r"^\s*[-=_~]{3,}\s*$"),
)

# Date token alternation reused by the report-date patterns:
# "June 22, 2026" | "06/22/2026" | "6/22/26" | "2026-06-22"
_DATE_TOKEN = r"([A-Za-z]{3,9}\.?\s+\d{1,2},\s*\d{4}|\d{1,2}/\d{1,2}/\d{2,4}|\d{4}-\d{2}-\d{2})"

# Tried in order over the lines above the first section header; group(1) is the
# date string. Labeled forms are preferred over a bare date line.
REPORT_DATE_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(rf"\bWeek\s+of\s+{_DATE_TOKEN}", re.IGNORECASE),
    re.compile(rf"\bReport\s+Date\s*:?\s*{_DATE_TOKEN}", re.IGNORECASE),
    re.compile(rf"\bfor\s+the\s+week\s+(?:of|ending)\s+{_DATE_TOKEN}", re.IGNORECASE),
    re.compile(rf"^\s*{_DATE_TOKEN}\s*$", re.IGNORECASE),  # bare date line near the top
)
REPORT_DATE_SEARCH_LINES = 40  # only look this far down for the report date

# Section headers: ordered (pattern, section_code). Each pattern must match the
# WHOLE line (tolerating case, "Section 3:"/"1." numbering prefixes, and a
# trailing colon). Underline decoration rows are already stripped by
# ARTIFACT_PATTERNS. Codes are the con.weekly_report_event.section values.
_HDR_PREFIX = r"^\s*(?:SECTION\s+)?(?:[IVX\d]+\s*[.):\-]\s*)?"
_HDR_SUFFIX = r"\s*:?\s*$"


def _hdr(words: str) -> re.Pattern:
    return re.compile(_HDR_PREFIX + words + _HDR_SUFFIX, re.IGNORECASE)


SECTION_PATTERNS: tuple[tuple[re.Pattern, str], ...] = (
    (_hdr(r"Letters?\s+of\s+Intent(?:\s+Received|\s+Filed)?"), "LETTER_OF_INTENT"),
    (_hdr(r"(?:New\s+Applications?(?:\s+Received|\s+Filed)?|Applications?\s+Received)"), "NEW_APPLICATION"),
    (_hdr(r"Withdrawn(?:\s+Applications?|\s+Projects?)?"), "WITHDRAWN_APPLICATION"),
    (_hdr(r"Pending\s+Applications?(?:\s+Under\s+Review)?"), "PENDING_APPLICATION"),
    (_hdr(r"(?:Recently\s+)?Approved(?:\s+Applications?|\s+Projects?)?"), "APPROVED"),
    (_hdr(r"(?:Recently\s+)?Denied(?:\s+Applications?|\s+Projects?)?"), "DENIED"),
    (_hdr(r"Appealed(?:\s+Projects?|\s+Applications?)?"), "APPEALED"),
    (_hdr(r"Letters?\s+of\s+Determination(?:\s+Issued)?"), "LETTER_OF_DETERMINATION"),
)
assert {code for _, code in SECTION_PATTERNS} == set(REPORT_SECTIONS)

# A new entry starts at a line carrying a "Project No."-style label (matched
# here) OR any docket reference (via common.docket.extract_dockets).
ENTRY_START_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^\s*(?:Project|Docket|File|Matter)\s+(?:No\.?|Number|#)", re.IGNORECASE),
)

# Field labels: ordered (field_name, label_pattern). Patterns match the LABEL
# only; the value runs from the end of the label to the next label on the same
# line (several "Label: value" pairs may share a line) or to end of line.
# "docket_label" swallows the "Project No.:" label so its value is not mistaken
# for description text (the docket itself is extracted from the whole entry).
FIELD_PATTERNS: tuple[tuple[str, re.Pattern], ...] = (
    ("docket_label", re.compile(r"\b(?:Project|Docket|File|Matter)\s+(?:No\.?|Number|#)\s*:?", re.IGNORECASE)),
    ("applicant", re.compile(r"\bApplicant\s*:", re.IGNORECASE)),
    ("project_description", re.compile(r"\bProject(?:\s+Description)?\s*:", re.IGNORECASE)),
    ("county", re.compile(r"\bCounty\s*:", re.IGNORECASE)),
    ("site", re.compile(r"\bSite\s*:", re.IGNORECASE)),
    ("cost", re.compile(r"\b(?:(?:Estimated|Est\.?|Total)\s+)?(?:Project\s+)?Cost\s*:", re.IGNORECASE)),
    ("opposition", re.compile(r"\bOpposition\s*:", re.IGNORECASE)),
    ("filing_date", re.compile(r"\b(?:Date\s+Filed|Filing\s+Date|Filed)\s*:", re.IGNORECASE)),
    ("decision_deadline", re.compile(r"\b(?:Decision\s+Due|Decision\s+Deadline|Review\s+Period\s+Ends)\s*:", re.IGNORECASE)),
    # "Withdrawn:" is treated as a decision-event date alongside Approved/Denied.
    ("decision_date", re.compile(r"\b(?:Decision\s+Date|Approved|Denied|Withdrawn)\s*:", re.IGNORECASE)),
)

# An unlabeled line that still LOOKS like "Some Label: value" (a label we do
# not know) is kept in raw_text only — it is not description prose.
UNKNOWN_LABEL_RE = re.compile(r"^\s*[A-Za-z][A-Za-z ./#()'-]{0,40}:\s")

# "Site: Macon, Bibb County" -> county "Bibb" (validated via match_county).
SITE_COUNTY_RE = re.compile(r",\s*([A-Za-z.' -]+?)\s+County\b", re.IGNORECASE)

# Date parsing: (token_pattern, strptime formats). Tokens are normalized
# (collapse whitespace, drop periods) before strptime. Order matters: the
# 4-digit-year slash form must be tried before the 2-digit-year form.
DATE_PATTERNS: tuple[tuple[re.Pattern, tuple[str, ...]], ...] = (
    (re.compile(r"\b[A-Za-z]{3,9}\.?\s+\d{1,2},\s*\d{4}\b"), ("%B %d, %Y", "%b %d, %Y")),
    (re.compile(r"\b\d{1,2}/\d{1,2}/\d{4}\b"), ("%m/%d/%Y",)),
    (re.compile(r"\b\d{1,2}/\d{1,2}/\d{2}\b(?!\d)"), ("%m/%d/%y",)),
    (re.compile(r"\b\d{4}-\d{2}-\d{2}\b"), ("%Y-%m-%d",)),
)

# Cost parsing: scaled word form first ("$4.5 million", "$1.2M"), then plain
# "$1,234,567.89", then a bare number when the whole value is numeric.
_COST_MULTIPLIERS: dict[str, Decimal] = {
    "K": Decimal(1_000),
    "THOUSAND": Decimal(1_000),
    "M": Decimal(1_000_000),
    "MILLION": Decimal(1_000_000),
    "B": Decimal(1_000_000_000),
    "BILLION": Decimal(1_000_000_000),
}
_COST_SCALED_RE = re.compile(
    r"\$?\s*(\d[\d,]*(?:\.\d+)?)\s*(thousand|million|billion|[KMB])(?![A-Za-z])", re.IGNORECASE
)
_COST_PLAIN_RE = re.compile(r"\$\s*(\d[\d,]*(?:\.\d+)?)")
_COST_BARE_RE = re.compile(r"^\s*(\d[\d,]*(?:\.\d+)?)\s*$")

_TWO_PLACES = Decimal("0.01")

STUB_COMPLETENESS_FLAGS = '["stub_from_weekly_report"]'

# ---------------------------------------------------------------------------
# Dataclasses (shapes per DESIGN.md)
# ---------------------------------------------------------------------------


@dataclass
class ReportEvent:
    section: str
    docket_raw: str | None
    docket_id: str | None
    applicant: str | None
    project_description: str | None
    county: str | None
    cost: Decimal | None
    opposition: str | None
    filing_date: date | None
    decision_deadline: date | None
    decision_date: date | None
    raw_text: str


@dataclass
class ReportParse:
    report_date: date | None
    events: list[ReportEvent]
    warnings: list[str]


@dataclass
class LoadStats:
    inserted: int
    skipped_duplicates: int
    stub_matters_created: int


# ---------------------------------------------------------------------------
# Text extraction
# ---------------------------------------------------------------------------


def extract_text(pdf_path: str) -> str:
    """Extract text from every page of the PDF, pages joined with form feed."""
    import pdfplumber  # lazy: pure parsing/tests must not require the PDF stack

    with pdfplumber.open(pdf_path) as pdf:
        return "\f".join((page.extract_text() or "") for page in pdf.pages)


# ---------------------------------------------------------------------------
# Scalar parsers (pure, unit-testable)
# ---------------------------------------------------------------------------


def parse_date(raw: str | None) -> date | None:
    """Parse "June 22, 2026", "06/22/2026", "6/22/26", or ISO. None if absent."""
    if not raw:
        return None
    for pattern, formats in DATE_PATTERNS:
        for m in pattern.finditer(raw):
            token = " ".join(m.group(0).replace(".", "").split())
            for fmt in formats:
                try:
                    return datetime.strptime(token, fmt).date()
                except ValueError:
                    continue
    return None


def parse_cost(raw: str | None) -> Decimal | None:
    """Parse "$1,234,567.89" or "$4.5 million" style amounts into Decimal."""
    if not raw:
        return None
    m = _COST_SCALED_RE.search(raw)
    if m:
        multiplier = _COST_MULTIPLIERS[m.group(2).upper()]
        try:
            return (Decimal(m.group(1).replace(",", "")) * multiplier).quantize(_TWO_PLACES)
        except InvalidOperation:
            return None
    m = _COST_PLAIN_RE.search(raw) or _COST_BARE_RE.match(raw)
    if m:
        try:
            return Decimal(m.group(1).replace(",", "")).quantize(_TWO_PLACES)
        except InvalidOperation:
            return None
    return None


def dedupe_hash(report_date: date | None, section: str, docket_raw: str | None, raw_text: str) -> str:
    """sha256 hex over (report_date|section|docket_raw|raw_text)."""
    key = "|".join(
        (
            report_date.isoformat() if report_date else "",
            section or "",
            docket_raw or "",
            raw_text or "",
        )
    )
    return hashlib.sha256(key.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Report parsing (pure)
# ---------------------------------------------------------------------------


def _clean_lines(text: str) -> list[str]:
    """Split into lines, dropping page-furniture lines (ARTIFACT_PATTERNS)."""
    lines: list[str] = []
    for raw_line in text.replace("\f", "\n").splitlines():
        line = raw_line.rstrip()
        if any(p.match(line) for p in ARTIFACT_PATTERNS):
            continue
        lines.append(line)
    return lines


def _match_section_header(line: str) -> str | None:
    for pattern, code in SECTION_PATTERNS:
        if pattern.match(line):
            return code
    return None


def _find_report_date(lines: list[str]) -> date | None:
    """Look for the report date in the lines above the first section header."""
    top: list[str] = []
    for line in lines:
        if _match_section_header(line):
            break
        top.append(line)
        if len(top) >= REPORT_DATE_SEARCH_LINES:
            break
    for pattern in REPORT_DATE_PATTERNS:
        for line in top:
            m = pattern.search(line)
            if m:
                parsed = parse_date(m.group(1))
                if parsed:
                    return parsed
    return None


def _split_sections(lines: list[str]) -> list[tuple[str, list[str]]]:
    """Split cleaned lines into (section_code, body_lines) in document order."""
    sections: list[tuple[str, list[str]]] = []
    current_code: str | None = None
    current_lines: list[str] = []
    for line in lines:
        code = _match_section_header(line)
        if code:
            if current_code is not None:
                sections.append((current_code, current_lines))
            current_code, current_lines = code, []
        elif current_code is not None:
            current_lines.append(line)
        # Lines before the first section header are report preamble; ignored.
    if current_code is not None:
        sections.append((current_code, current_lines))
    return sections


def _is_entry_start(line: str) -> bool:
    if any(p.search(line) for p in ENTRY_START_PATTERNS):
        return True
    return bool(extract_dockets(line))


def _split_entries(section_lines: list[str]) -> list[list[str]]:
    """Split a section body into entry blocks.

    An entry starts at a line with a docket reference or a "Project No."-style
    label; other non-blank lines attach to the current entry. Lines before the
    first entry (column headings etc.) are ignored.
    """
    entries: list[list[str]] = []
    current: list[str] | None = None
    for line in section_lines:
        if not line.strip():
            continue
        if _is_entry_start(line):
            if current:
                entries.append(current)
            current = [line]
        elif current is not None:
            current.append(line)
    if current:
        entries.append(current)
    return entries


def _label_hits(line: str) -> list[tuple[int, int, str]]:
    """All non-overlapping field-label matches in a line, sorted by position."""
    hits: list[tuple[int, int, str]] = []
    for field_name, pattern in FIELD_PATTERNS:
        for m in pattern.finditer(line):
            hits.append((m.start(), m.end(), field_name))
    hits.sort(key=lambda t: (t[0], -t[1]))  # prefer the longer label on ties
    kept: list[tuple[int, int, str]] = []
    last_end = -1
    for start, end, name in hits:
        if start >= last_end:
            kept.append((start, end, name))
            last_end = end
    return kept


def _strip_docket_text(text: str) -> str:
    """Remove docket substrings from a prose fragment; return what remains."""
    for dm in extract_dockets(text):
        text = text.replace(dm.raw, " ")
    return " ".join(text.split())


def _parse_entry(section: str, entry_lines: list[str], warn) -> ReportEvent:
    raw_text = "\n".join(entry_lines).strip()
    values: dict[str, list[str]] = {}
    desc_parts: list[str] = []

    for line in entry_lines:
        stripped = line.strip()
        if not stripped:
            continue
        hits = _label_hits(stripped)
        if not hits:
            # Unlabeled line: docket-only lines vanish; unknown "Label: value"
            # lines stay in raw_text only; prose becomes description text.
            if UNKNOWN_LABEL_RE.match(stripped):
                continue
            remainder = _strip_docket_text(stripped).strip(" \t-–—:,")
            if remainder:
                desc_parts.append(remainder)
            continue
        lead = stripped[: hits[0][0]].strip()
        if lead:  # text before the first label (e.g. a docket) — not prose
            lead = _strip_docket_text(lead).strip(" \t-–—:,")
            if lead:
                desc_parts.append(lead)
        for idx, (start, end, name) in enumerate(hits):
            value_end = hits[idx + 1][0] if idx + 1 < len(hits) else len(stripped)
            value = stripped[end:value_end].strip(" \t;,-–—")
            values.setdefault(name, []).append(value)

    def first(name: str) -> str | None:
        for v in values.get(name, []):
            if v.strip():
                return v.strip()
        return None

    # Docket: first extract_dockets hit anywhere in the entry.
    dockets = extract_dockets(raw_text)
    if dockets:
        docket_id: str | None = dockets[0].canonical
        docket_raw: str | None = dockets[0].raw
    else:
        docket_id = docket_raw = None
        warn(f"{section}: entry has no recognizable docket: {entry_lines[0].strip()!r}")

    applicant = first("applicant")

    labeled_desc = [v for v in values.get("project_description", []) if v.strip()]
    description = " ".join(labeled_desc + desc_parts).strip() or None

    # County: prefer "County:"; fall back to "Site: <city>, <county> County".
    county: str | None = None
    county_raw = first("county")
    if county_raw:
        county = match_county(county_raw.strip(" .;,"))
        if county is None:
            warn(f"{section}: unrecognized county {county_raw!r} ({docket_raw or 'no docket'})")
    if county is None:
        site_raw = first("site")
        if site_raw:
            m = SITE_COUNTY_RE.search(site_raw)
            if m:
                county = match_county(m.group(1))
                if county is None:
                    warn(f"{section}: unrecognized county in site {site_raw!r}")

    cost_raw = first("cost")
    cost = parse_cost(cost_raw)
    if cost_raw and cost is None:
        warn(f"{section}: unparseable cost {cost_raw!r} ({docket_raw or 'no docket'})")

    def date_field(name: str) -> date | None:
        raw = first(name)
        parsed = parse_date(raw)
        if raw and parsed is None:
            warn(f"{section}: unparseable {name} {raw!r} ({docket_raw or 'no docket'})")
        return parsed

    return ReportEvent(
        section=section,
        docket_raw=docket_raw,
        docket_id=docket_id,
        applicant=applicant,
        project_description=description,
        county=county,
        cost=cost,
        opposition=first("opposition"),
        filing_date=date_field("filing_date"),
        decision_deadline=date_field("decision_deadline"),
        decision_date=date_field("decision_date"),
        raw_text=raw_text,
    )


def parse_report_text(text: str, report_file: str = "") -> ReportParse:
    """Parse extracted report text into ReportParse. Pure — no I/O, no DB."""
    warnings: list[str] = []
    prefix = f"{report_file}: " if report_file else ""

    def warn(message: str) -> None:
        warnings.append(prefix + message)

    lines = _clean_lines(text or "")

    report_date = _find_report_date(lines)
    if report_date is None:
        warn("report date not found near the top of the report")

    sections = _split_sections(lines)
    if not sections:
        warn("no report sections recognized")

    events: list[ReportEvent] = []
    for code, section_lines in sections:
        for entry_lines in _split_entries(section_lines):
            events.append(_parse_entry(code, entry_lines, warn))

    return ReportParse(report_date=report_date, events=events, warnings=warnings)


# ---------------------------------------------------------------------------
# Loading (DB writes; parameterized T-SQL only)
# ---------------------------------------------------------------------------

_MATTER_EXISTS_SQL = "SELECT 1 FROM con.matter WHERE docket_id = ?"
_MATTER_STUB_INSERT_SQL = (
    "INSERT INTO con.matter (docket_id, completeness_flags) "
    "SELECT ?, ? WHERE NOT EXISTS (SELECT 1 FROM con.matter WHERE docket_id = ?)"
)
_VARIANT_EXISTS_SQL = "SELECT 1 FROM con.matter_docket_variant WHERE docket_id = ? AND variant = ?"
_VARIANT_INSERT_SQL = (
    "INSERT INTO con.matter_docket_variant (docket_id, variant) "
    "SELECT ?, ? WHERE NOT EXISTS ("
    "SELECT 1 FROM con.matter_docket_variant WHERE docket_id = ? AND variant = ?)"
)
_EVENT_EXISTS_SQL = "SELECT 1 FROM con.weekly_report_event WHERE dedupe_hash = ?"
_EVENT_INSERT_SQL = (
    "INSERT INTO con.weekly_report_event ("
    "report_date, report_file, section, docket_id, docket_raw, applicant, "
    "project_description, county, cost, opposition, filing_date, "
    "decision_deadline, decision_date, raw_text, dedupe_hash) "
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
)


def _docket_variants(event: ReportEvent) -> tuple[str, ...]:
    """Variants for the event's docket (re-derived from the printed form)."""
    dm = normalize_docket(event.docket_raw or "")
    if dm:
        return dm.variants
    return tuple(sorted({v for v in (event.docket_raw, event.docket_id) if v}))


def load_events(conn, parse: ReportParse, report_file: str) -> LoadStats:
    """Insert parsed events; create stub matters for unknown canonical dockets.

    - Stub matters are INSERT ... WHERE NOT EXISTS only; existing matters are
      never updated. Docket variants are insert-if-missing.
    - Events are skipped on dedupe_hash match (guard SELECT, not exception
      parsing). Events without a docket insert with docket_id NULL.
    - Raises ValueError when parse.report_date is None (column is NOT NULL).
    """
    if parse.report_date is None:
        raise ValueError("cannot load events: report_date was not found in the report")

    inserted = 0
    skipped_duplicates = 0
    stub_matters_created = 0
    ensured_matters: set[str] = set()
    cur = conn.cursor()

    for event in parse.events:
        event_hash = dedupe_hash(parse.report_date, event.section, event.docket_raw, event.raw_text)
        cur.execute(_EVENT_EXISTS_SQL, event_hash)
        if cur.fetchone() is not None:
            skipped_duplicates += 1
            continue

        if event.docket_id and event.docket_id not in ensured_matters:
            ensured_matters.add(event.docket_id)
            cur.execute(_MATTER_EXISTS_SQL, event.docket_id)
            if cur.fetchone() is None:
                cur.execute(
                    _MATTER_STUB_INSERT_SQL,
                    event.docket_id,
                    STUB_COMPLETENESS_FLAGS,
                    event.docket_id,
                )
                stub_matters_created += 1
            for variant in _docket_variants(event):
                cur.execute(_VARIANT_EXISTS_SQL, event.docket_id, variant)
                if cur.fetchone() is None:
                    cur.execute(_VARIANT_INSERT_SQL, event.docket_id, variant, event.docket_id, variant)

        cur.execute(
            _EVENT_INSERT_SQL,
            parse.report_date,
            report_file or None,
            event.section,
            event.docket_id,
            event.docket_raw,
            event.applicant,
            event.project_description,
            event.county,
            event.cost,
            event.opposition,
            event.filing_date,
            event.decision_deadline,
            event.decision_date,
            event.raw_text,
            event_hash,
        )
        inserted += 1

    conn.commit()
    return LoadStats(
        inserted=inserted,
        skipped_duplicates=skipped_duplicates,
        stub_matters_created=stub_matters_created,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _event_to_jsonable(event: ReportEvent) -> dict:
    out = asdict(event)
    for key, value in out.items():
        if isinstance(value, date):
            out[key] = value.isoformat()
        elif isinstance(value, Decimal):
            out[key] = str(value)
    return out


def _print_summary(parse: ReportParse, report_file: str) -> None:
    print(f"report_file:  {report_file}")
    print(f"report_date:  {parse.report_date.isoformat() if parse.report_date else 'NOT FOUND'}")
    print(f"events:       {len(parse.events)}")
    counts: dict[str, int] = {}
    for event in parse.events:
        counts[event.section] = counts.get(event.section, 0) + 1
    for section in REPORT_SECTIONS:
        if section in counts:
            print(f"  {section:<24} {counts[section]}")
    no_docket = sum(1 for e in parse.events if e.docket_id is None)
    if no_docket:
        print(f"events without docket: {no_docket}")
    if parse.warnings:
        print(f"warnings ({len(parse.warnings)}):")
        for warning in parse.warnings:
            print(f"  - {warning}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="python -m ingest.weekly_report_parser",
        description="Parse a GA DCH weekly CON Tracking Report PDF (and optionally load it).",
    )
    ap.add_argument("pdf", help="path to the weekly CON Tracking Report PDF")
    ap.add_argument("--apply", action="store_true", help="load events into the database")
    ap.add_argument("--out", help="write parsed events to this JSON file")
    args = ap.parse_args(argv)

    report_file = os.path.basename(args.pdf)
    text = extract_text(args.pdf)
    parse = parse_report_text(text, report_file=report_file)
    _print_summary(parse, report_file)

    if args.out:
        payload = {
            "report_file": report_file,
            "report_date": parse.report_date.isoformat() if parse.report_date else None,
            "warnings": parse.warnings,
            "events": [_event_to_jsonable(e) for e in parse.events],
        }
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
            fh.write("\n")
        print(f"wrote {len(parse.events)} events to {args.out}")

    if args.apply:
        from common.db import get_connection  # lazy: pyodbc only needed with --apply

        try:
            stats = load_events(get_connection(), parse, report_file)
        except ValueError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        print(
            f"loaded: inserted={stats.inserted} "
            f"skipped_duplicates={stats.skipped_duplicates} "
            f"stub_matters_created={stats.stub_matters_created}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
