"""Georgia CON Tagging Taxonomy — Axis 1-4 controlled vocabularies.

These constants mirror the seed data in schema/migrations/0010_axis_vocab.sql and
0011_axis_tag_tables.sql (same convention as common/vocab.py: the codes stored in the
database are these exact strings). Source of truth: GeorgiaCONTaggingTaxonomy_2.docx
(Axis 3 = the 100-900 series; Axis 4 = the P100-P900 series).
"""

# ruff: noqa: E501 -- verbatim taxonomy labels/citations; wrapping would corrupt them.

from dataclasses import dataclass


@dataclass(frozen=True)
class AxisCode:
    """One Axis 3/4 entry: a key-number code with its parent, label, and citation."""

    code: str
    parent_code: str | None
    label: str
    citation: str | None
    sort_order: int


# Axis 1 -- Proceeding Type (single-select). code -> description (None if self-explanatory).
AXIS1_PROCEEDING_TYPE: dict[str, str | None] = {
    "CON": "Includes Letters of Intent (LOIs).",
    "DET": None,
    "DET-ASC": "Includes LNR-ASC filings prior to 2019.",
    "DET-EQT": "Includes LNR-EQT filings prior to 2019.",
    "Other": "Rare escape hatch; use sparingly, not as a default.",
}

# Axis 2 -- Authority Type (single-select, incl. Masterfile). code -> description.
AXIS2_AUTHORITY_TYPE: dict[str, str | None] = {
    "Statute": None,
    "Rule": None,
    "DCH Desk Decision": None,
    "CON Appeals Panel Decision": None,
    "OSAH ALJ Decision": None,
    "DCH Commissioner Final Order": None,
    "Superior Court Opinion": None,
    "GA Court of Appeals Opinion": None,
    "GA Supreme Court Opinion": None,
    "Application (non-authority)": None,
    "Additional Information (non-authority)": None,
    "Masterfile": "Selecting this value excludes every other Axis 2 value and suppresses Axis 3/4 tags for the document.",
}

MASTERFILE = "Masterfile"

# AXIS3_SUBSTANTIVE_ISSUE: tuple of AxisCode, in taxonomy-document order.
AXIS3_SUBSTANTIVE_ISSUE: tuple[AxisCode, ...] = (
    AxisCode(code="100", parent_code=None, label="Reviewability & Jurisdiction", citation=None, sort_order=0),
    AxisCode(code="110", parent_code="100", label="New/expanded/relocated facility construction", citation="§ 31-6-40(a)(1)", sort_order=1),
    AxisCode(code="111", parent_code="100", label="Equipment purchase or lease trigger", citation="§ 31-6-40(a)(3)", sort_order=2),
    AxisCode(code="112", parent_code="100", label="Bed capacity increase trigger", citation="§ 31-6-40(a)(4)", sort_order=3),
    AxisCode(code="113", parent_code="100", label="New clinical health service / \"12-month rule\"", citation="§ 31-6-40(a)(5)", sort_order=4),
    AxisCode(code="114", parent_code="100", label="Conversion or upgrade to specialty hospital / facility-type conversion", citation="§ 31-6-40(a)(6)", sort_order=5),
    AxisCode(code="115", parent_code="100", label="New service at a diagnostic/treatment/rehab center (radiation therapy, biliary lithotripsy, OR surgery, cardiac cath)", citation="§ 31-6-40(a)(7)", sort_order=6),
    AxisCode(code="116", parent_code="100", label="Destination cancer hospital ↔ general cancer hospital conversion", citation="§ 31-6-40(a)(8), § 31-6-40.3", sort_order=7),
    AxisCode(code="117", parent_code="100", label="Redistribution of already-licensed beds (not a reviewable event)", citation="Premier Health Care Invs. v. UHS of Anchor, 310 Ga. 32 (2020)", sort_order=8),
    AxisCode(code="118", parent_code="100", label="Relocation of an existing facility/service", citation="§ 31-6-47(a)(24); HCA Health Servs. v. Roach, 263 Ga. 798 (1994); North Fulton Med. Ctr. v. Stephenson, 269 Ga. 540 (1998)", sort_order=9),
    AxisCode(code="119", parent_code="100", label="Grandfathered / pre-program status", citation="HCA Health Servs. v. Roach, 263 Ga. 798 (1994)", sort_order=10),
    AxisCode(code="120", parent_code="100", label="New and emerging health care service / moratorium", citation="§ 31-6-40(e)", sort_order=11),
    AxisCode(code="130", parent_code="100", label="Facility/service definitional disputes", citation="§ 31-6-2", sort_order=12),
    AxisCode(code="200", parent_code=None, label="Exemptions & Non-Reviewability", citation=None, sort_order=13),
    AxisCode(code="210", parent_code="200", label="Government/institutional exemptions", citation="§ 31-6-47(a)(1)–(5)", sort_order=14),
    AxisCode(code="220", parent_code="200", label="Physician/dentist office exemption", citation="§ 31-6-47(a)(4)", sort_order=15),
    AxisCode(code="230", parent_code="200", label="Pre-application cost exemptions", citation="§ 31-6-47(a)(6)–(8)", sort_order=16),
    AxisCode(code="240", parent_code="200", label="Restructuring/acquisition exemption", citation="§ 31-6-47(a)(9)", sort_order=17),
    AxisCode(code="250", parent_code="200", label="Equipment acquisition/replacement/repair exemption", citation="§ 31-6-47(a)(10), (28)", sort_order=18),
    AxisCode(code="260", parent_code="200", label="Safety-hazard capital expenditure exemption", citation="§ 31-6-47(a)(11)", sort_order=19),
    AxisCode(code="270", parent_code="200", label="Cost-overrun exemption", citation="§ 31-6-47(a)(12)", sort_order=20),
    AxisCode(code="280", parent_code="200", label="Equipment transfer-between-facilities exemption", citation="§ 31-6-47(a)(13)", sort_order=21),
    AxisCode(code="290", parent_code="200", label="HMO-related exemption", citation="§ 31-6-47(a)(14)", sort_order=22),
    AxisCode(code="2A0", parent_code="200", label="Bed capacity exemption (lesser of 10 beds/20% rule)", citation="§ 31-6-47(a)(15)", sort_order=23),
    AxisCode(code="2B0", parent_code="200", label="Nonclinical project exemption", citation="§ 31-6-47(a)(16)", sort_order=24),
    AxisCode(code="2C0", parent_code="200", label="Life plan community skilled-nursing exemption", citation="§ 31-6-47(a)(17)", sort_order=25),
    AxisCode(code="2D0", parent_code="200", label="Single-specialty ASC exemption", citation="§ 31-6-47(a)(18)", sort_order=26),
    AxisCode(code="2E0", parent_code="200", label="Joint-venture ASC exemption", citation="§ 31-6-47(a)(19)", sort_order=27),
    AxisCode(code="2F0", parent_code="200", label="Imaging center population-needs-methodology exemption", citation="§ 31-6-47(a)(20)", sort_order=28),
    AxisCode(code="2G0", parent_code="200", label="Cardiac catheterization exemptions (diagnostic/adult; C-PORT study)", citation="§ 31-6-47(a)(21)–(22)", sort_order=29),
    AxisCode(code="2H0", parent_code="200", label="Correctional-facility infirmary exemption", citation="§ 31-6-47(a)(23)", sort_order=30),
    AxisCode(code="2I0", parent_code="200", label="Relocation exemption (SNF/ICF/micro-hospital)", citation="§ 31-6-47(a)(24)", sort_order=31),
    AxisCode(code="2J0", parent_code="200", label="Traumatic brain injury facility exemption", citation="§ 31-6-47(a)(25)", sort_order=32),
    AxisCode(code="2K0", parent_code="200", label="Hospital remodel/renovate/replace capital exemption", citation="§ 31-6-47(a)(26)", sort_order=33),
    AxisCode(code="2L0", parent_code="200", label="General renovation/refurbishment exemption", citation="§ 31-6-47(a)(27)", sort_order=34),
    AxisCode(code="2M0", parent_code="200", label="Primary-campus capital expenditure exemption", citation="§ 31-6-47(a)(29)", sort_order=35),
    AxisCode(code="2N0", parent_code="200", label="Letter-of-determination eligibility & scope", citation="§ 31-6-47.1; r. 111-2-2-.10(1)(a)–(b), (2)", sort_order=36),
    AxisCode(code="2O0", parent_code="200", label="Exemption compliance conditions", citation="indigent/charity care & Medicaid participation percentages — § 31-6-40(c)(2)", sort_order=37),
    AxisCode(code="2P0", parent_code="200", label="Penalty/revocation for exemption noncompliance", citation="§ 31-6-47.1(b)", sort_order=38),
    AxisCode(code="300", parent_code=None, label="Application Eligibility", citation=None, sort_order=39),
    AxisCode(code="310", parent_code="300", label="Outstanding-obligations bar to new/modified CON", citation="§ 31-6-42.1", sort_order=40),
    AxisCode(code="400", parent_code=None, label="Review Standards & Criteria (the § 31-6-42(a) considerations)", citation=None, sort_order=41),
    AxisCode(code="410", parent_code="400", label="State health plan consistency", citation="§ 31-6-42(a)(1)", sort_order=42),
    AxisCode(code="420", parent_code="400", label="General/population need", citation="§ 31-6-42(a)(2); Doctors Hosp. of Augusta v. DCH, 350 Ga. App. 36 (2019); Univ. Health Servs. v. Ga. DCH, 2026 Ga. App. LEXIS 139", sort_order=43),
    AxisCode(code="430", parent_code="400", label="Existing/less-costly alternatives", citation="§ 31-6-42(a)(3)", sort_order=44),
    AxisCode(code="440", parent_code="400", label="Financial feasibility", citation="§ 31-6-42(a)(4)", sort_order=45),
    AxisCode(code="450", parent_code="400", label="Payor impact", citation="§ 31-6-42(a)(5)", sort_order=46),
    AxisCode(code="460", parent_code="400", label="Construction cost & energy-conservation reasonableness", citation="§ 31-6-42(a)(6)", sort_order=47),
    AxisCode(code="470", parent_code="400", label="Financial & physical accessibility", citation="§ 31-6-42(a)(7)", sort_order=48),
    AxisCode(code="480", parent_code="400", label="Positive relationship to / adverse impact on existing delivery system", citation="§ 31-6-42(a)(8); Tanner Med. Ctr. v. Vest Newnan, 337 Ga. App. 884 (2016); Hospital Auth. v. State Health Planning Agency, 211 Ga. App. 407 (1993)", sort_order=49),
    AxisCode(code="490", parent_code="400", label="Efficient utilization of proposing facility", citation="§ 31-6-42(a)(9)", sort_order=50),
    AxisCode(code="4A0", parent_code="400", label="Out-of-service-area patient base", citation="§ 31-6-42(a)(10)", sort_order=51),
    AxisCode(code="4B0", parent_code="400", label="Biomedical/behavioral research or national/regional service development", citation="§ 31-6-42(a)(11)", sort_order=52),
    AxisCode(code="4C0", parent_code="400", label="Health professional training program needs", citation="§ 31-6-42(a)(12)", sort_order=53),
    AxisCode(code="4D0", parent_code="400", label="Innovation, quality assurance, cost-effectiveness, competition", citation="§ 31-6-42(a)(13)", sort_order=54),
    AxisCode(code="4E0", parent_code="400", label="HMO special needs", citation="§ 31-6-42(a)(14)", sort_order=55),
    AxisCode(code="4F0", parent_code="400", label="Minimum quality standards / accreditation / volume thresholds", citation="§ 31-6-42(a)(15)", sort_order=56),
    AxisCode(code="4G0", parent_code="400", label="Resource availability (staffing, management)", citation="§ 31-6-42(a)(16)", sort_order=57),
    AxisCode(code="4H0", parent_code="400", label="Underrepresented health service preference", citation="§ 31-6-42(a)(17)", sort_order=58),
    AxisCode(code="4I0", parent_code="400", label="Osteopathic medicine need determination", citation="§ 31-6-42(b)", sort_order=59),
    AxisCode(code="4J0", parent_code="400", label="Destination cancer hospital-specific criteria", citation="§ 31-6-42(b.1)", sort_order=60),
    AxisCode(code="4K0", parent_code="400", label="Sole-provider perinatal county exception", citation="§ 31-6-42(b.2)", sort_order=61),
    AxisCode(code="4L0", parent_code="400", label="Minority-administered hospital extraordinary consideration", citation="§ 31-6-42(c)", sort_order=62),
    AxisCode(code="4M0", parent_code="400", label="Atypical/geographic barrier exception", citation="Kennestone Hosp. v. DCH, 346 Ga. App. 70 (2018); ASMC, LLC v. Northside Hosp., 344 Ga. App. 576 (2018); Ga. DCH v. Satilla Health Servs., 2004 Ga. App. LEXIS 376", sort_order=63),
    AxisCode(code="4N0", parent_code="400", label="Department's obligation to specify applicable considerations & evidentiary support", citation="§ 31-6-42(e)", sort_order=64),
    AxisCode(code="4O0", parent_code="400", label="Comparative batching priority factors as applied (which factor controlled the tie-break)", citation="r. 111-2-2-.08(1)(h)", sort_order=65),
    AxisCode(code="500", parent_code=None, label="Facility & Service-Specific Review Standards", citation=None, sort_order=66),
    AxisCode(code="510", parent_code="500", label="Short-stay general hospital beds", citation="demand-based bed-need forecasting model; 50,000-person minimum target service area for a new hospital; trauma center / teaching hospital / sole community provider / critical access / hospital-closure exceptions to need and adverse-impact standards — r. 111-2-2-.20", sort_order=67),
    AxisCode(code="511", parent_code="500", label="Adult cardiac catheterization", citation="minimum 1,040 procedures/year service-area threshold; 100-procedure minimum performance standard — r. 111-2-2-.21", sort_order=68),
    AxisCode(code="512", parent_code="500", label="Adult open heart surgery", citation="minimum 300 procedures/year projected within 3 years; existing-service floor of 200 procedures/year; 250-procedure adult cath feeder-volume threshold — r. 111-2-2-.22", sort_order=69),
    AxisCode(code="513", parent_code="500", label="Pediatric cardiac catheterization & open heart surgery", citation="750 procedures/year per authorized service; 150 additional pediatric procedures/year within 3 years; 100-procedure pediatric cardiac surgery minimum — r. 111-2-2-.23", sort_order=70),
    AxisCode(code="514", parent_code="500", label="Perinatal services / freestanding birthing centers", citation="r. 111-2-2-.24 (see also 4K0 sole-provider exception)", sort_order=71),
    AxisCode(code="515", parent_code="500", label="Psychiatric & substance abuse services", citation="r. 111-2-2-.26. Repealed — see Appendix A. Flag any decision citing this as pre-repeal.", sort_order=72),
    AxisCode(code="520", parent_code="500", label="Skilled nursing / intermediate care facilities", citation="bed-need ratios (0.43 / 9.77 / 32.5 / 120.00 beds per 1,000 projected resident population by age cohort); minimum facility size thresholds (60 beds rural freestanding / 100 beds urban freestanding / 10 beds rural hospital-based / 20 beds urban hospital-based) — r. 111-2-2-.30", sort_order=73),
    AxisCode(code="521", parent_code="500", label="Personal care homes", citation="25-bed minimum; bed-need ratios (18.00 / 40.00 / 60.00 per 1,000 projected resident population) — r. 111-2-2-.31", sort_order=74),
    AxisCode(code="522", parent_code="500", label="Home health services", citation="geographic service area definition (contiguous-county grouping); unmet-need determination by service area; population-based need formula (4/5/45/185 patients per 1,000 by age cohort); 250/500-patient batching thresholds — r. 111-2-2-.32", sort_order=75),
    AxisCode(code="523", parent_code="500", label="Life plan community (LPC) sheltered nursing facilities", citation="modified initial-implementation duration rule — r. 111-2-2-.33", sort_order=76),
    AxisCode(code="524", parent_code="500", label="Traumatic brain injury facilities", citation="demand-based need methodology (2% transitional-living / 0.5% life-long-living demand factors); 85% occupancy standard; 6-bed minimum, 30-bed life-long-living cap — r. 111-2-2-.34", sort_order=77),
    AxisCode(code="525", parent_code="500", label="Comprehensive inpatient physical rehabilitation", citation="minimum 5-day/week multidisciplinary programming intensity; 85% capacity standard for bed-need projection; 20%-of-capacity/10-bed expansion exception at >60% occupancy; tiered minimum bed sizes; 50-mile/75,000-population exception — r. 111-2-2-.35", sort_order=78),
    AxisCode(code="526", parent_code="500", label="Long-term care hospitals", citation="occupancy-rate definition; short-stay-bed-to-LTCH conversion/reversion mechanics; official inventory effects; 1.3% demand factor with 6% rehab-overlap reduction, 85% capacity standard — r. 111-2-2-.36", sort_order=79),
    AxisCode(code="530", parent_code="500", label="Ambulatory surgery centers", citation="OR capacity standard (1,000 patients/OR/year, based on 250 OR-days × 4 procedures/day); need methodology combining hospital-dedicated and freestanding ASC OR counts — r. 111-2-2-.40", sort_order=80),
    AxisCode(code="531", parent_code="500", label="PET units", citation="optimal utilization defined as 2,750 scans/year — r. 111-2-2-.41", sort_order=81),
    AxisCode(code="532", parent_code="500", label="Mega-voltage radiation therapy", citation="separate standards for non-special-purpose vs. special-purpose MRT; 45-mile minimum distance from existing/approved unit; 150-patient/year minimum projected volume — r. 111-2-2-.42", sort_order=82),
    AxisCode(code="540", parent_code="500", label="Destination / general cancer hospitals", citation="§ 31-6-40.3, § 31-6-42(b.1)", sort_order=83),
    AxisCode(code="550", parent_code="500", label="Freestanding emergency departments", citation="Ga. DCH v. Houston Hosps., 365 Ga. App. 751 (2022); AU Med. Ctr. v. Ga. DCH, 366 Ga. App. 94 (2022)", sort_order=84),
    AxisCode(code="560", parent_code="500", label="Rural health facilities / micro-hospitals", citation="§ 31-6-2(23.2)", sort_order=85),
    AxisCode(code="600", parent_code=None, label="Enforcement, Revocation & Penalties", citation=None, sort_order=86),
    AxisCode(code="610", parent_code="600", label="Revocation grounds (§ 31-6-45(a), elaborated at r. 111-2-2-.05(1)(a): false information, financial-obligation failure, implementation/performance-standard failure, unauthorized ownership transfer, unauthorized location change, condition noncompliance, late/incomplete reporting, unpaid fines, quality-standard failure, Medicaid-participation failure)", citation=None, sort_order=87),
    AxisCode(code="620", parent_code="600", label="Location-change protection against revocation", citation="§ 31-6-45(a) proviso", sort_order=88),
    AxisCode(code="630", parent_code="600", label="Untimely implementation revocation", citation="§ 31-6-45(a.1); r. 111-2-2-.05(1)(f)", sort_order=89),
    AxisCode(code="640", parent_code="600", label="Operating without a CON", citation="license denial consequence — § 31-6-45(b); r. 111-2-2-.05(2)(a)", sort_order=90),
    AxisCode(code="650", parent_code="600", label="Civil penalties for unauthorized operation", citation="§ 31-6-45(c); r. 111-2-2-.05(2)(b)", sort_order=91),
    AxisCode(code="660", parent_code="600", label="Injunctive relief & third-party standing to enforce", citation="§ 31-6-45(d); r. 111-2-2-.05(2)(g); Diversified Health Mgt. Servs. v. Visiting Nurses Ass'n, 254 Ga. 500 (1985)", sort_order=92),
    AxisCode(code="670", parent_code="600", label="Departmental investigations & records production", citation="§ 31-6-45(e); r. 111-2-2-.05(3); Southeast Ga. Health Sys. v. Berry, 362 Ga. App. 422 (2022)", sort_order=93),
    AxisCode(code="680", parent_code="600", label="Automatic revocation tied to license revocation", citation="§ 31-6-45.1; r. 111-2-2-.05(1)(e)", sort_order=94),
    AxisCode(code="690", parent_code="600", label="Medicaid participation condition & penalty for termination", citation="§ 31-6-45.2; r. 111-2-2-.05(2)(d)", sort_order=95),
    AxisCode(code="6A0", parent_code="600", label="Res judicata effects on reapplication", citation="State Health Planning Agency v. Cribb Indus., 204 Ga. App. 285 (1992)", sort_order=96),
    AxisCode(code="6B0", parent_code="600", label="Late-notification-of-acquisition penalty ($500/day)", citation="r. 111-2-2-.05(2)(c)", sort_order=97),
    AxisCode(code="700", parent_code=None, label="Appeal & Judicial Review — Standing, Merits Doctrine", citation=None, sort_order=98),
    AxisCode(code="710", parent_code="700", label="Standing/right to appeal a department decision (who qualifies, including the 30-day filing requirement as part of the doctrinal test)", citation="§ 31-6-44(d); ProHealth Home Health-Ga. v. Ga. DCH, 377 Ga. App. 600 (2025); Loyd v. Ga. State Health Planning & Dev. Agency, 168 Ga. App. 850 (1983)", sort_order=99),
    AxisCode(code="720", parent_code="700", label="Intervention", citation="timeliness and requirements — § 31-6-44(d); r. 274-1-.03(2); Redmond Park Hosp. v. Floyd Health Care Mgmt., 360 Ga. App. 469 (2021)", sort_order=100),
    AxisCode(code="730", parent_code="700", label="Substantial-justification / delay-or-harassment findings on the merits of an appeal", citation="§ 31-6-44(f)(2)–(3); r. 274-1-.11(2)", sort_order=101),
    AxisCode(code="735", parent_code="700", label="Commissioner-stage fee-shifting for appeals lacking substantial justification", citation="historical only (r. 274-1-.13(6)–(7), (9), now repealed with no statutory replacement — § 31-6-44's commissioner-review subsections were themselves deleted in 2024). Tag pre-July-2024 dockets only.", sort_order=102),
    AxisCode(code="740", parent_code="700", label="New/additional evidence admissibility at hearing; new-need-study limitation", citation="§ 31-6-44(g); r. 274-1-.10(9)–(11); Palmyra Park Hosp. v. Phoebe Sumter Med. Ctr., 310 Ga. App. 487 (2011)", sort_order=103),
    AxisCode(code="745", parent_code="700", label="Scope of the appeal hearing", citation="the § 31-6-44(f) issue-for-decision list as the operative boundary, plus § 31-6-47.1(a)'s separate routing of reviewability/determination disputes to the general GAPA track", sort_order=104),
    AxisCode(code="750", parent_code="700", label="Ex parte contact", citation="what constitutes prejudicial contact — § 31-6-44(h); North Fulton Cmty. Hosp. v. State Health Planning & Dev. Agency, 168 Ga. App. 801 (1983)", sort_order=105),
    AxisCode(code="760", parent_code="700", label="\"Competent substantial evidence\" / deference standard applied to Commissioner review of hearing officer findings", citation="historical only (see Appendix B). Tag pre-July-2024 CON Appeals Panel/Commissioner decisions: Vantage Cancer Ctrs. of Ga. v. Ga. DCH, 318 Ga. 361 (2024); Ga. DCH v. Houston Hosps., 372 Ga. App. 218 (2024); Northside Hosp. v. Northeast Ga. Med. Ctr., 373 Ga. App. 714 (2024)", sort_order=106),
    AxisCode(code="770", parent_code="700", label="\"Particularity\" requirement for Commissioner departure from hearing officer findings", citation="historical only, same basis as 760. Vantage Cancer Ctrs. of Ga. v. Ga. DCH, 318 Ga. 361 (2024)", sort_order=107),
    AxisCode(code="775", parent_code="700", label="Judicial review standard", citation="the six statutory grounds for reversal/modification, the \"substantial evidence\" standard's express elevation above \"any evidence\" — § 31-6-44.1(a)", sort_order=108),
    AxisCode(code="780", parent_code="700", label="CON Act vs. general APA", citation="which procedural regime controls — Redmond Park Hosp. v. Floyd Health Care Mgmt., 360 Ga. App. 469 (2021)", sort_order=109),
    AxisCode(code="790", parent_code="700", label="Exhaustion of administrative remedies (futility exception; \"acting outside statutory authority\" exception)", citation="§ 50-13-19(a); Ga. DCH v. Ga. Soc'y of Ambulatory Surgery Ctrs., 290 Ga. 628 (2012); Ga. Soc'y of Ambulatory Surgery Ctrs. v. Ga. DCH, 316 Ga. App. 433 (2012)", sort_order=110),
    AxisCode(code="7A0", parent_code="700", label="Venue", citation="Tanner Med. Ctr. v. Vest Newnan, 337 Ga. App. 884 (2016)", sort_order=111),
    AxisCode(code="7B0", parent_code="700", label="Agency as proper party respondent to judicial review", citation="Loyd v. Ga. State Health Planning & Dev. Agency, 168 Ga. App. 850 (1983)", sort_order=112),
    AxisCode(code="7C0", parent_code="700", label="Judicial deference to agency health-planning expertise", citation="Ga. DCH v. Satilla Health Servs., 2004 Ga. App. LEXIS 376", sort_order=113),
    AxisCode(code="7D0", parent_code="700", label="Superior Court fee-shifting for the prevailing party, including the \"jurisdiction\" carve-out's meaning", citation="fully live, self-sufficient statutory text — § 31-6-44.1(c); Lakeview Behavioral Health Sys. v. UHS Peachford, 321 Ga. App. 820 (2013); Tanner Med. Ctr. v. Vest Newnan, 344 Ga. App. 901 (2018)", sort_order=114),
    AxisCode(code="7E0", parent_code="700", label="Deemed-affirmed-by-operation-of-law at the Superior Court stage (120/90/30-day mechanics)", citation="§ 31-6-44.1(b); Kennestone Hosp. v. Cartersville Med. Ctr., 341 Ga. App. 28 (2017); Doctors Hosp. of Augusta v. DCH, 344 Ga. App. 583 (2018)", sort_order=115),
    AxisCode(code="800", parent_code=None, label="Constitutional & Property-Rights Issues", citation=None, sort_order=116),
    AxisCode(code="810", parent_code="800", label="CON as a vested private property right", citation="Kennestone Hosp. v. Emory Univ., 318 Ga. 169 (2024), rev'd 373 Ga. App. 114 (2024)", sort_order=117),
    AxisCode(code="820", parent_code="800", label="Anti-Competitive Contracts Clause challenges", citation="Women's Surgical Ctr. v. Berry, 302 Ga. 349 (2017)", sort_order=118),
    AxisCode(code="830", parent_code="800", label="Vagueness challenges to CON rules", citation="Ga. DCH v. Northside Hosp., 295 Ga. 446 (2014)", sort_order=119),
    AxisCode(code="840", parent_code="800", label="Legitimate legislative purpose / rational basis for CON program", citation="Women's Surgical Ctr. v. Berry, 302 Ga. 349 (2017)", sort_order=120),
    AxisCode(code="850", parent_code="800", label="No vested right to operate a converted facility type", citation="Emory Univ. v. Kennestone Hosp., 373 Ga. App. 114 (2024)", sort_order=121),
    AxisCode(code="900", parent_code=None, label="Reporting & Transparency", citation=None, sort_order=122),
    AxisCode(code="910", parent_code="900", label="Facility annual reporting requirements", citation="§ 31-6-70; r. 111-2-2-.04", sort_order=123),
    AxisCode(code="920", parent_code="900", label="DCH annual report to General Assembly / state health plan updates", citation="§ 31-6-46", sort_order=124),
)

# AXIS4_PROCEDURAL_ISSUE: tuple of AxisCode, in taxonomy-document order.
AXIS4_PROCEDURAL_ISSUE: tuple[AxisCode, ...] = (
    AxisCode(code="P100", parent_code=None, label="Pre-Filing & Intent", citation=None, sort_order=0),
    AxisCode(code="P110", parent_code="P100", label="Letter of intent", citation="25-day pre-filing requirement — § 31-6-43(a)", sort_order=1),
    AxisCode(code="P120", parent_code="P100", label="Notice of intent to apply (batching-specific", citation="25 calendar days from unmet-need publication) — r. 111-2-2-.08(1)(c)", sort_order=2),
    AxisCode(code="P130", parent_code="P100", label="Determination-request form requirements (one matter per request, $500 fee, fee waivers for hospital authorities/nonprofits)", citation="r. 111-2-2-.10(1)", sort_order=3),
    AxisCode(code="P200", parent_code=None, label="Application Completeness & Amendment", citation=None, sort_order=4),
    AxisCode(code="P210", parent_code="P200", label="Completeness determination & deficiency notice", citation="§ 31-6-43(b); r. 111-2-2-.07(1)(a)", sort_order=5),
    AxisCode(code="P220", parent_code="P200", label="30-day applicant meeting / 45-day additional-information deadline", citation="r. 111-2-2-.07(1)(f)", sort_order=6),
    AxisCode(code="P230", parent_code="P200", label="Amendment vs. new-application distinction (90-day amendment deadline; qualifying changes)", citation="r. 111-2-2-.07(1)(f)–(g)", sort_order=7),
    AxisCode(code="P240", parent_code="P200", label="Withdrawal of application (including deemed-withdrawal on total scope/location/applicant change)", citation="r. 111-2-2-.07(1)(g)", sort_order=8),
    AxisCode(code="P300", parent_code=None, label="Batching & Comparative Review Procedure", citation=None, sort_order=9),
    AxisCode(code="P310", parent_code="P300", label="Unmet-need determination & batching cycle announcement (6-month review cycle)", citation="r. 111-2-2-.08(1)(a)–(b)", sort_order=10),
    AxisCode(code="P320", parent_code="P300", label="Notice-of-intent-to-apply qualification & disqualification", citation="r. 111-2-2-.08(1)(c)", sort_order=11),
    AxisCode(code="P330", parent_code="P300", label="Joinder procedure & 25-day joinder window", citation="§ 31-6-43(f); r. 111-2-2-.07(1)(c), -.08(1)", sort_order=12),
    AxisCode(code="P400", parent_code=None, label="Opposition & Public Participation Mechanics", citation=None, sort_order=13),
    AxisCode(code="P410", parent_code="P400", label="Notice of opposition form (30-day deadline; vendor-lobbyist certification requirement)", citation="r. 111-2-2-.07(1)(h), -.08(1)(g)(4)", sort_order=14),
    AxisCode(code="P420", parent_code="P400", label="Opposition meeting logistics (no earlier than 60th day; one spokesperson; no applicant rebuttal)", citation="§ 31-6-43(h); r. 111-2-2-.07(1)(h)(1)", sort_order=15),
    AxisCode(code="P430", parent_code="P400", label="Substantive opposition comment procedure", citation="single-application rule & applicant response deadline (75th day) — r. 111-2-2-.07(1)(h)(2)–(3)", sort_order=16),
    AxisCode(code="P440", parent_code="P400", label="Public hearing request procedure (50-resident petition; 20-day request deadline; non-party testimony status)", citation="r. 111-2-2-.07(1)(e)", sort_order=17),
    AxisCode(code="P450", parent_code="P400", label="Third-party/government notice obligations (newspaper, regional commission, county/municipal officials)", citation="§ 31-6-43(b); r. 111-2-2-.07(1)(a)", sort_order=18),
    AxisCode(code="P500", parent_code=None, label="Review Timeline, Deadlines & Decision Content", citation=None, sort_order=19),
    AxisCode(code="P510", parent_code="P500", label="Standard 120-day review clock", citation="§ 31-6-43(d)(1); r. 111-2-2-.07(1)(b)", sort_order=20),
    AxisCode(code="P520", parent_code="P500", label="30-day extension to 150 days for good cause", citation="§ 31-6-43(d)(1); r. 111-2-2-.07(1)(d)", sort_order=21),
    AxisCode(code="P530", parent_code="P500", label="Deemed-approved-by-default (121st/151st day)", citation="§ 31-6-43(j); r. 111-2-2-.07(2)(f)", sort_order=22),
    AxisCode(code="P540", parent_code="P500", label="Emergency/expedited review (30-day cycle; telephone authorization; automatic approval on default)", citation="§ 31-6-43(k); r. 111-2-2-.07(1)(i), (k)–(o)", sort_order=23),
    AxisCode(code="P550", parent_code="P500", label="Decision letter content requirements (findings per consideration; appeal-availability notice)", citation="§ 31-6-43(i); r. 111-2-2-.07(2)(c)", sort_order=24),
    AxisCode(code="P600", parent_code=None, label="Determination (DET/LNR) Procedure", citation=None, sort_order=25),
    AxisCode(code="P610", parent_code="P600", label="Determination request form, fee, and one-matter-per-request rule", citation="r. 111-2-2-.10(1)", sort_order=26),
    AxisCode(code="P620", parent_code="P600", label="60-day determination review clock / 30-day extension to 90 days", citation="§ 31-6-47.1(a); r. 111-2-2-.10(2)(c)", sort_order=27),
    AxisCode(code="P630", parent_code="P600", label="Non-precedential, fact-specific scope of determinations", citation="r. 111-2-2-.10(1)(a)", sort_order=28),
    AxisCode(code="P640", parent_code="P600", label="Equipment determination", citation="sworn affidavit & completion/interim reporting requirements (DET-EQT) — r. 111-2-2-.10(3)", sort_order=29),
    AxisCode(code="P650", parent_code="P600", label="ASC determination", citation="ownership/utilization/specialty documentation requirements (DET-ASC) — r. 111-2-2-.10(4)", sort_order=30),
    AxisCode(code="P660", parent_code="P600", label="Notice of and opposition to determination requests", citation="§ 31-6-47.1(a); r. 111-2-2-.10(2)(d)", sort_order=31),
    AxisCode(code="P670", parent_code="P600", label="Determination validity limits (non-transferable; invalidated by changed facts)", citation="r. 111-2-2-.10(3)(f)", sort_order=32),
    AxisCode(code="P700", parent_code=None, label="Hearing Scheduling & Filing Mechanics (CON Appeal Panel)", citation=None, sort_order=33),
    AxisCode(code="P710", parent_code="P700", label="Hearing/intervention request", citation="30-day filing deadline; intervention request due within 10 days of the hearing request — § 31-6-44(d); r. 274-1-.03(2)", sort_order=34),
    AxisCode(code="P715", parent_code="P700", label="Appeal filing fee", citation="$7,500 per party per application, rural-hospital-denial exemption, intervenor payment within 14 days — r. 274-1-.04", sort_order=35),
    AxisCode(code="P720", parent_code="P700", label="Hearing officer appointment & scheduling (60–120 day hearing window; 14-day scheduling conference and notice)", citation="§ 31-6-44(d); r. 274-1-.06", sort_order=36),
    AxisCode(code="P725", parent_code="P700", label="Hearing location", citation="r. 274-1-.08 (repealed; no statutory replacement identified — treat current status as uncertain)", sort_order=37),
    AxisCode(code="P730", parent_code="P700", label="De novo evidentiary hearing procedural framework under GAPA contested-case rules", citation="§ 31-6-44(e); r. 274-1-.10(1)", sort_order=38),
    AxisCode(code="P732", parent_code="P700", label="Pre-hearing discovery mechanics (10-business-day discovery response; as-of-right discovery categories)", citation="r. 274-1-.10(2)", sort_order=39),
    AxisCode(code="P734", parent_code="P700", label="Pre-hearing brief and written direct testimony requirements (8-page summary limit; expert witness written direct testimony in lieu of live direct)", citation="r. 274-1-.10(3)–(6)", sort_order=40),
    AxisCode(code="P736", parent_code="P700", label="Order of proceeding & burden of proof allocation", citation="r. 274-1-.10(7)–(8)", sort_order=41),
    AxisCode(code="P740", parent_code="P700", label="Remand procedure & deadline-setting", citation="§ 31-6-44(g); r. 274-1-.11(7)", sort_order=42),
    AxisCode(code="P750", parent_code="P700", label="Findings of fact/conclusions of law", citation="30-day post-hearing filing deadline (extendable up to 15 additional days for complexity) — § 31-6-44(i); r. 274-1-.11(1)", sort_order=43),
    AxisCode(code="P755", parent_code="P700", label="Optional Commissioner-designee review filing mechanics", citation="30-day objection deadline; 61-day finality-by-default absent objection — r. 274-1-.12. Live and operative: the Appeals Panel serves as the Commissioner's designee for this rule. The substantive review standard the designee applies is unconfirmed (see Appendix B).", sort_order=44),
    AxisCode(code="P760", parent_code="P700", label="Record maintenance & cost-sharing for hearing record preparation", citation="r. 274-1-.19 (repealed; no statutory replacement identified — treat current status as uncertain)", sort_order=45),
    AxisCode(code="P800", parent_code=None, label="Post-Decision & Enforcement Procedure", citation=None, sort_order=46),
    AxisCode(code="P810", parent_code="P800", label="Revocation notice & GAPA hearing procedure", citation="§ 31-6-45(a); r. 111-2-2-.05(1)(a)–(b)", sort_order=47),
    AxisCode(code="P820", parent_code="P800", label="120-day reapplication bar after final revocation/denial", citation="r. 111-2-2-.05(1)(c)", sort_order=48),
    AxisCode(code="P830", parent_code="P800", label="Voluntary revocation request (without prejudice)", citation="r. 111-2-2-.05(1)(d)", sort_order=49),
    AxisCode(code="P840", parent_code="P800", label="Automatic revocation timing tied to license-revocation finality", citation="§ 31-6-45.1; r. 111-2-2-.05(1)(e)", sort_order=50),
    AxisCode(code="P850", parent_code="P800", label="Fine assessment, notice, and 30/90-day payment deadlines", citation="§ 31-6-45(c); r. 111-2-2-.05(2)(b), (f)", sort_order=51),
    AxisCode(code="P860", parent_code="P800", label="Department's right to inspect/audit", citation="r. 111-2-2-.05(3)", sort_order=52),
    AxisCode(code="P870", parent_code="P800", label="Progress/periodic reporting deadlines (180-day report rule)", citation="§ 31-6-70; r. 111-2-2-.04, -.05(1)(f)(2)", sort_order=53),
    AxisCode(code="P900", parent_code=None, label="Judicial Review Mechanics", citation=None, sort_order=54),
    AxisCode(code="P910", parent_code="P900", label="Judicial review filing procedure", citation="§ 31-6-44.1(a)–(b)", sort_order=55),
    AxisCode(code="P920", parent_code="P900", label="Stay of CON effectiveness pending judicial review", citation="r. 111-2-2-.07(2)(h)", sort_order=56),
    AxisCode(code="P930", parent_code="P900", label="Finality determination for appeal-clock purposes (when a decision becomes \"final\")", citation="§ 31-6-44(j); r. 111-2-2-.05(1)(c)", sort_order=57),
    AxisCode(code="P940", parent_code="P900", label="Record transmission deadline (30 days) & Superior Court hearing/decision timing (120-day deemed-affirmed rule)", citation="§ 31-6-44.1(b)", sort_order=58),
)

AXIS3_BY_CODE: dict[str, AxisCode] = {e.code: e for e in AXIS3_SUBSTANTIVE_ISSUE}
AXIS4_BY_CODE: dict[str, AxisCode] = {e.code: e for e in AXIS4_PROCEDURAL_ISSUE}

